title: Huaquan Yang's Homepage
page-top-title: Huaquan Yang
top-section-bg-text: geomorphology
home-subtitle: Huaquan Yang&ensp;|&ensp;杨华铨
copyright-text: '&copy; Huaquan Yang 2023-2024. All Rights Reserved.'
